version: '3'

services:
  base_php:
    image: casr-php
    build:
      context: ./docker/images/web
      dockerfile: Dockerfile
  web:
    build: docker/compose/web
    expose:
      - 9000
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www:cached
    tty: true
    depends_on:
      - db
    links:
      - redis
    stdin_open: true
    environment:
      XDEBUG_CONFIG: "remote_connect_back=1; remote_enable=1;"
      PHP_IDE_CONFIG: "serverName=docker-server-casr"
    networks:
      - code-network
    restart: on-failure

  db:
    build: docker/compose/db
    user: "1000:1000"
    ports:
      - 3306:3306
    volumes:
      - ./docker/compose/db/data:/var/lib/mysql
      - ./docker/compose/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    networks:
      - code-network
    restart: on-failure

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./docker/compose/redis/data:/data
    entrypoint: redis-server --appendonly yes
    networks:
      - code-network
    restart: on-failure

networks:
  code-network:
    driver: bridge
